language: python
sudo: required
dist: trusty

addons:
  apt:
    packages:
    - git
    - mosquitto

python:
  - "2.7"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install -e .
  - pip install coverage coveralls pytest-cov

script:
  py.test -v --cov  flask_mqtt

after_success:
  coveralls
