language: python
sudo: required
dist: trusty

addons:
  apt:
    packages:
    - git
    - mosquitto
   
python:
  - "2.7"
  - "3.5"

# command to install dependencies
install:
  - pip install .
  - pip install coverage

script:
  pytest

after_success:
  coveralls
